#version 460
#extension GL_EXT_ray_tracing : require

layout(location = 0) rayPayloadEXT int hitValue;

layout(binding = 0) uniform accelerationStructureEXT tlas;
layout(binding = 1) buffer tensor { int result[]; };

void main() {
    uint id = gl_LaunchIDEXT.x * 9
            + gl_LaunchIDEXT.y * 3
            + gl_LaunchIDEXT.z;
    //id 13 will set dir to zero -> skip that one
    if (id == 13) {
        result[id] = 0;
        return;
    }

    vec3 dir = normalize(vec3(gl_LaunchIDEXT) - vec3(1.0));
    traceRayEXT(
        tlas,
        gl_RayFlagsOpaqueEXT,   //flags
        0xFF,                   //cull mask
        0,                      //SBT record offset
        0,                      //SBT record stride
        1,                      //miss index
        vec3(0.0),              //origin
        0.0,                    //t_min
        dir,                    //direction
        10.0,                   //t_max
        0                       //payload
    );

    result[id] = hitValue;
}
